steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ss-scraper:$SHORT_SHA'
      - '.'

  # 2. Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/ss-scraper:$SHORT_SHA'

  # 3. Deploy to Cloud Run using built-in substitutions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ss-scraper'
      - '--image=gcr.io/$PROJECT_ID/ss-scraper:$SHORT_SHA'
      - '--region=europe-north1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=ss-scraper-run-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-secrets=TELEGRAM_WEBHOOK_SECRET=projects/$PROJECT_NUMBER/secrets/TELEGRAM_WEBHOOK_SECRET:latest,DB_URL=projects/$PROJECT_NUMBER/secrets/DB_URL:latest,TELEGRAM_BOT_TOKEN=projects/$PROJECT_NUMBER/secrets/TELEGRAM_BOT_TOKEN:latest,TELEGRAM_CHAT_ID=projects/$PROJECT_NUMBER/secrets/TELEGRAM_CHAT_ID:latest'

images:
  - 'gcr.io/$PROJECT_ID/ss-scraper:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'